Move Agent Msgs to the SDK
PickNikRobotics/moveit_studio_sdk pull request #22
Opened 2023-12-05 15:49 UTC by eholum

Moving these to the SDK to provide external callers to programmatic access to additional msgs used by the agent.

2023-12-05 17:50 UTC, adlarkin requested changes
CI build is currently failing:
```
#12 3.303 ERROR: the following packages/stacks could not have their rosdep keys resolved
#12 3.303 to system dependencies:
#12 3.303 moveit_studio_agent_msgs: Cannot locate rosdep definition for [moveit_task_constructor_msgs]
```

I think we need to copy over the agent msgs in the Dockerfile: https://github.com/PickNikRobotics/moveit_studio_sdk/blob/b2b1994dbabd675192c49aa78fd64355aa1b2307/Dockerfile#L13-L14

We should also add the agent msgs to the `moveit_studio_msgs` metapackage: https://github.com/PickNikRobotics/moveit_studio_sdk/blob/8d4da42f2d9840adcfb2f2fe651be6bfc8f24e9a/moveit_studio_msgs/moveit_studio_msgs/package.xml#L12-L13

2023-12-06 16:52 UTC, adlarkin reviewed
Looks good! Before we merge this, take a look at my comments in the core Studio PR. I wonder if we want to add a few more messages/services to this package before merging.

2023-12-06 16:57 UTC, adlarkin approved these changes
After a quick discussion elsewhere, this is ready to go :grin: :shipit:

2023-12-06 17:03 UTC, sea-bass approved these changes

2023-12-06 17:03 UTC, sea-bass commented on moveit_studio_msgs/moveit_studio_agent_msgs/msg/LicenseInfo.msg
> +int8  UNKNOWN = 6
why are these double spaced?

2023-12-06 20:12 UTC, eholum commented on moveit_studio_msgs/moveit_studio_agent_msgs/msg/LicenseInfo.msg
> +int8  UNKNOWN = 6
Fixed!

2023-12-06 20:14 UTC, merged